### ISSUE TITLE
Segfault in srw

### ISSUE THREAD

**Issue by CFGrote** [samoylv/WPG#74] opened 2016-05-23 11:32 UTC
[wpg_debug.zip](https://github.com/samoylv/WPG/files/277362/wpg_debug.zip)

I get a segfault in in srTGenOptElem::GetCellDataForInterpol  at sroptelm.h:348. To reproduce, extract attached container and run WavePropagatorTest_debug.py after adjusting the path to wpg in line 5.

Here's a trace of a gdb session to locate the exception.

See also [https://github.com/eucall-software/simex_platform/issues/39].

**Comment by buzmakov** [comment] 2016-05-27 12:17
Segfault happens only with python2.
Python3 work fine.

**Comment by samoylv** [comment] 2016-05-27 12:20
does it mean that there is a problem with memory allocation on python2?

**Comment by buzmakov** [comment] 2016-05-27 12:21
Hmm, on second run script work fine without segfault.

**Comment by buzmakov** [comment] 2016-05-27 12:23
No, this is not a problem with memory.

**Comment by CFGrote** [comment] 2016-05-27 12:24
i observed the same, does not segfault in every run. this is typical for
memory misallocation.


On 05/27/2016 02:21 PM, Alexey Buzmakov wrote:
> Hmm, on second run script work fine without segfault.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/samoylv/WPG/issues/74#issuecomment-222132510>, or
> mute the thread
> <https://github.com/notifications/unsubscribe/AOwoRzkbHRoOldn1Dh9Tuvo7zVb4UtLMks5qFuHDgaJpZM4Ikbvz>.
> 

-- 
--
Carsten Fortmann-Grote
Scientist
European XFEL GmbH

Mail: carsten.grote@xfel.eu
Phone: +49 (0)40 8998 5603

**Comment by CFGrote** [comment] 2016-05-27 12:26
how can you be sure?

On 05/27/2016 02:23 PM, Alexey Buzmakov wrote:
> No, this is not a problem with memory.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/samoylv/WPG/issues/74#issuecomment-222132991>, or
> mute the thread
> <https://github.com/notifications/unsubscribe/AOwoR2tuVIDqav3hx1rrldKEBbPNoaYGks5qFuJYgaJpZM4Ikbvz>.
> 

-- 
--
Carsten Fortmann-Grote
Scientist
European XFEL GmbH

Mail: carsten.grote@xfel.eu
Phone: +49 (0)40 8998 5603

**Comment by buzmakov** [comment] 2016-05-27 12:30
I can't be absolutely sure, but have feel that problem with building wavefront from hdf5.
We have similar problem with hdf5 file, when order of reading values has matter.

**Comment by samoylv** [comment] 2016-09-06 09:51
@CFGrote: could you provide more details on the environment? I was not able to reproduce the segmentation fault neither with Python 3.4 on my Macbook, not with Python 2.7 on the server.

I use the script and data you provide with reading the WF from hdf5 file

**Comment by samoylv** [comment] 2016-09-14 16:26
I installed simex_platform in reduced form (only WPG module) at the xfel server and was not able to reproduce the segmentation fault error with Python 2.7, it runs smoothly for hdf5 file. 
@CFGrote  At what machine did you observe  the behaviour? Can we meet briefly and look at that?

**Comment by CFGrote** [comment] 2016-09-14 19:55
sure. i'm a bit on and off this week due to daughter starting
kindergarden. what's your day look like tomorrow? around 3pm?

carsten

Dr. Carsten Fortmann-Grote
Scientist for Scientific Simulations / Wissenschaftler fuer
wissenschaftliche Simulationen
European XFEL GmbH
Holzkoppel 4
22869 Schenefeld
Germany

Phone: +49 (0)40 8998-5603
Fax:   +49 (0)40 8998-1905
Email: carsten.grote@xfel.eu
Web: www.xfel.eu

Managing Directors: Prof. Dr. Massimo Altarelli, Dr. Claudia Burger

Registered as European X-Ray Free-Electron Laser Facility GmbH
at Amtsgericht Hamburg, HRB 111165

**Comment by samoylv** [comment] 2016-09-15 05:46
Ok, let's try

**Comment by samoylv** [comment] 2016-10-14 13:21
waiting for reproducible environment, closing now

**Closed by samoylv** 2016-10-14 13:21 UTC
